import {state,xpToLevel,reviewerRank} from '../state.js';
import {esc,cover,empty} from '../ui.js';

const me=()=>state.user;
const ownWorks=()=>state.works.filter(work=>work.authorId===me()?.id);
const tabButton=(id,label)=>`<button data-action="profile-tab" data-tab="${id}" class="${state.ui.profileTab===id?'active':''}">${label}</button>`;
const chips=items=>items?.length?`<div class="profile-chips">${items.map(item=>`<span>${esc(item)}</span>`).join('')}</div>`:'<p class="muted">Пока не указано</p>';

function workCards(works){return works.length?works.map(work=>`<article class="profile-work card">${cover(work)}<div><h3>${esc(work.title)}</h3><p>v${esc(work.version)} · ${esc(work.writingStatus||'draft')}</p><div class="actions"><button data-action="studio-select" data-id="${work.id}">Редактировать</button><button class="primary" data-action="analytics" data-id="${work.id}">Аналитика</button></div></div></article>`).join(''):empty('Здесь пока пусто','Работы появятся после создания или публикации.');}
function overview(){const user=me();return `<div class="profile-overview"><section class="card profile-about"><h2>О пользователе</h2><p>${esc(user.bio||'Пользователь ещё не добавил описание.')}</p><h3>Интересы</h3>${chips(user.interests)}<h3>Любимые жанры</h3>${chips(user.wantedGenreNames)}<h3>Любимые темы</h3>${chips(user.favoriteTopics)}</section><aside class="stack"><section class="card"><h3>Любимые книги</h3>${user.favoriteBooks?.length?user.favoriteBooks.map(book=>`<div class="favorite-book"><b>${esc(book.title)}</b><small>${esc(book.author_name||'Автор не указан')}</small></div>`).join(''):'<p class="muted">Книги не добавлены</p>'}</section><section class="card"><h3>Ссылки</h3><div class="social-links">${user.socialLinks?.map(link=>`<a href="${esc(link.url)}" target="_blank" rel="noopener noreferrer">${esc(link.label||link.platform)}</a>`).join('')||'<span class="muted">Ссылок нет</span>'}</div></section></aside></div>`;}
function achievements(){const items=me().achievements||[];return `<section class="card"><h2>Достижения</h2><div class="achievement-grid">${items.map(item=>`<article class="achievement ${item.earned_at?'earned':'locked'}"><span>${esc(item.icon)}</span><div><b>${esc(item.name)}</b><p>${esc(item.description)}</p><small>${item.earned_at?'Получено':`${item.progress||0} / ${item.condition_value}`}</small><div class="achievement-progress"><i style="width:${Math.min(100,(item.progress||0)/item.condition_value*100)}%"></i></div></div></article>`).join('')||'<p class="muted">Каталог достижений пока пуст.</p>'}</div></section>`;}
function tabContent(){const user=me(),works=ownWorks();switch(state.ui.profileTab){case'overview':return overview();case'posts':{const posts=state.posts.filter(post=>post.authorId===user.id||post.author===user.name);return posts.length?posts.map(post=>`<article class="card"><p>${esc(post.text)}</p></article>`).join(''):empty('Пока нет постов','Создайте первый пост.');}case'written':return workCards(works.filter(work=>work.publicationStatus==='published'||work.writingStatus==='completed'));case'writing':return workCards(works.filter(work=>work.publicationStatus!=='published'&&work.writingStatus!=='completed'));case'read':return workCards(state.library.completed.map(id=>state.works.find(work=>work.id===id)).filter(Boolean));case'reviews':{const reviews=state.reviews.filter(review=>review.authorId===user.id);return reviews.length?reviews.map(review=>`<article class="card"><b>${review.rating} / 5</b><p>${esc(review.comment)}</p></article>`).join(''):empty('Нет рецензий','Оцените первое произведение.');}case'achievements':return achievements();default:return overview();}}

export function profileView(){const user=me();const avatar=user.avatarUrl?`<img src="${esc(user.avatarUrl)}" alt="">`:esc((user.nickname||user.name||'?')[0].toUpperCase());return `<section class="profile-v2"><div class="profile-banner" style="${user.bannerUrl?`background-image:url('${esc(user.bannerUrl)}')`:''}"></div><div class="profile-identity"><div class="profile-avatar-v2">${avatar}</div><div class="profile-main"><span class="profile-status">${esc(user.currentStatus||'В FRAKTUM')}</span><h1>${esc(user.nickname||user.name)} ${user.verified?'<span class="verified" aria-label="Верифицированный автор">✓</span>':''}</h1><p>@${esc(user.username)}${user.firstName||user.lastName?` · ${esc([user.firstName,user.lastName].filter(Boolean).join(' '))}`:''}</p><div class="profile-meta"><span>${user.role==='author'?'Автор':'Читатель'}</span><span>${reviewerRank(user.reputation)}</span><span>Уровень ${xpToLevel(user.xp)} · ${user.xp} XP</span></div></div><div class="profile-actions"><button class="primary" data-action="edit-profile">Редактировать профиль</button></div></div><div class="profile-counts"><span><b>${user.followers||0}</b> подписчиков</span><span><b>${user.following||0}</b> подписок</span><span><b>${user.reputation||0}</b> репутация</span></div></section><div class="tabs profile-tabs">${tabButton('overview','Профиль')}${tabButton('posts','Посты')}${user.role==='author'?tabButton('written','Написанные')+tabButton('writing','Пишущиеся'):''}${tabButton('read','Прочитанные')}${tabButton('reviews','Рецензии')}${tabButton('achievements','Достижения')}</div><section class="profile-content">${tabContent()}</section>`;}
